/**
 * DirectionalScenariosPanel — read-only panel for backend-exported directional
 * scenarios in Entries Lab.
 *
 * These are NOT entry-model scenarios (penetration / triggered-edge). They are
 * cross-model directional composites generated by the backtester in a split-pass
 * run (one simulate_trades() call per direction, merged by the backtester, then
 * exported as directional CSVs).
 *
 * Data source: activeRun.directionalResults (set by the importer).
 *
 * Rendering:
 *   - Renders null when no directional results exist.
 *   - One card per scenario in scenarioMeta, sorted by Net R descending.
 *   - Stats are computed inline from tradesByScenario — no external analytics hook.
 */

import React, { useMemo } from "react";
import { formatDirectionalScenarioLabel } from "../analytics/entryFormatters";

// ── Helpers ───────────────────────────────────────────────────────────────────

function getR(t) {
    const v = t?.r_multiple ?? t?.rMultiple ?? t?.r ?? null;
    return v == null ? null : Number(v);
}

function computeBasicStats(trades) {
    if (!Array.isArray(trades) || !trades.length) {
        return { netR: 0, tradeCount: 0, winRate: null, profitFactor: null, expectancy: null, maxDD: null, longCount: 0, shortCount: 0, longNetR: 0, shortNetR: 0 };
    }
    let wins = 0, losses = 0, grossW = 0, grossL = 0;
    let peak = 0, equity = 0, maxDD = 0;
    let longCount = 0, shortCount = 0, longNetR = 0, shortNetR = 0;

    for (const t of trades) {
        const r = getR(t) ?? 0;
        equity += r;
        if (equity > peak) peak = equity;
        const dd = peak - equity;
        if (dd > maxDD) maxDD = dd;
        if (r > 0) { wins++; grossW += r; }
        else if (r < 0) { losses++; grossL += Math.abs(r); }
        const dir = String(t?.direction || "").toLowerCase();
        if (dir === "long") { longCount++; longNetR += r; }
        else if (dir === "short") { shortCount++; shortNetR += r; }
    }

    const decisiveCount = wins + losses;
    return {
        netR: equity,
        tradeCount: trades.length,
        winRate: decisiveCount > 0 ? (wins / decisiveCount) * 100 : null,
        profitFactor: grossL > 0 ? grossW / grossL : null,
        expectancy: trades.length > 0 ? equity / trades.length : null,
        maxDD: maxDD > 0 ? maxDD : null,
        longCount,
        shortCount,
        longNetR,
        shortNetR,
    };
}

function fmtR(v) {
    if (v == null || !Number.isFinite(Number(v))) return "—";
    return `${v >= 0 ? "+" : ""}${Number(v).toFixed(2)}R`;
}

function fmtPct(v) {
    if (v == null || !Number.isFinite(Number(v))) return "—";
    return `${Number(v).toFixed(1)}%`;
}

function fmtPF(v) {
    if (v == null || !Number.isFinite(Number(v))) return "—";
    return Number(v).toFixed(2);
}

const LOW_N_THRESHOLD = 15;

// ── DirectionalScenariosPanel ─────────────────────────────────────────────────

export function DirectionalScenariosPanel({ activeRun }) {
    const scenarios = useMemo(() => {
        const dr = activeRun?.directionalResults;
        if (!dr?.tradesByScenario || !dr?.scenarioMeta) return [];
        return Object.entries(dr.scenarioMeta)
            .map(([storageKey, meta]) => {
                const trades = dr.tradesByScenario[storageKey] || [];
                const stats  = computeBasicStats(trades);
                return { storageKey, meta, stats };
            })
            .sort((a, b) => b.stats.netR - a.stats.netR);
    }, [activeRun]);

    if (!scenarios.length) return null;

    return (
        <div className="space-y-3">
            {/* Panel header */}
            <div className="flex items-center gap-3 flex-wrap">
                <span className="text-[10px] font-ui uppercase tracking-[0.15em] text-[hsl(var(--accent-primary))]">
                    Backend Directional Scenarios
                </span>
                <span className="px-1.5 py-0.5 text-[8px] font-ui uppercase tracking-wider border border-[hsl(var(--accent-primary)/0.5)] text-[hsl(var(--accent-primary))] clip-bevel-sm">
                    Backend
                </span>
                <span className="px-1.5 py-0.5 text-[8px] font-ui uppercase tracking-wider border border-[hsl(var(--text-2)/0.4)] text-[hsl(var(--text-2))] clip-bevel-sm">
                    Split-pass
                </span>
            </div>

            <p className="text-[10px] font-ui text-muted-lab leading-relaxed">
                True split-pass directional scenarios exported by the backtester.
                Supported for <span className="text-[hsl(var(--text-2))]">one_per_direction</span> and <span className="text-[hsl(var(--text-2))]">allow_multi_position</span>.{" "}
                <span className="opacity-60">single_position is blocked by the backend.</span>
            </p>

            {/* Scenario cards */}
            <div className="space-y-2">
                {scenarios.map(({ storageKey, meta, stats }) => {
                    const { scenarioId, executionMode, longKey, shortKey } = meta;
                    const isSupported = executionMode === "one_per_direction"
                        || executionMode === "allow_multi_position";
                    const modeLabel = executionMode === "one_per_direction" ? "One/dir"
                        : executionMode === "allow_multi_position"  ? "Multi"
                        : executionMode === "single_position"       ? "Single"
                        : (executionMode || "—");
                    const isLowN = stats.tradeCount < LOW_N_THRESHOLD;

                    return (
                        <div
                            key={storageKey}
                            className="border border-[hsl(var(--border-soft))] bg-[hsl(var(--panel-2)/0.12)] clip-bevel-sm px-3 py-2.5 space-y-2"
                        >
                            {/* Label + badges */}
                            <div className="flex items-center gap-2 flex-wrap">
                                <span className="text-[11.5px] font-ui font-medium text-[hsl(var(--text))]">
                                    {formatDirectionalScenarioLabel(scenarioId)}
                                </span>
                                <span className="px-1.5 py-0.5 text-[8px] font-ui uppercase tracking-wider border border-[hsl(var(--accent-primary)/0.45)] text-[hsl(var(--accent-primary))] clip-bevel-sm">
                                    Backend
                                </span>
                                <span className="px-1.5 py-0.5 text-[8px] font-ui uppercase tracking-wider border border-[hsl(var(--text-2)/0.4)] text-[hsl(var(--text-2))] clip-bevel-sm">
                                    Split-pass
                                </span>
                                <span className="px-1.5 py-0.5 text-[8px] font-ui uppercase tracking-wider border border-[hsl(var(--border-mid))] text-muted-lab clip-bevel-sm">
                                    {modeLabel}
                                </span>
                                {isSupported ? (
                                    <span className="px-1.5 py-0.5 text-[8px] font-ui uppercase tracking-wider border border-[hsl(var(--success)/0.5)] text-[hsl(var(--success))] clip-bevel-sm">
                                        Supported ✓
                                    </span>
                                ) : (
                                    <span className="px-1.5 py-0.5 text-[8px] font-ui uppercase tracking-wider border border-[hsl(var(--danger)/0.5)] text-[hsl(var(--danger))] clip-bevel-sm">
                                        ⚠ Unsupported
                                    </span>
                                )}
                                {isLowN && (
                                    <span className="px-1.5 py-0.5 text-[8px] font-ui uppercase tracking-wider border border-[hsl(var(--warning)/0.5)] text-[hsl(var(--warning))] clip-bevel-sm">
                                        Low sample
                                    </span>
                                )}
                            </div>

                            {/* Side keys */}
                            {(longKey || shortKey) && (
                                <div className="flex items-center gap-3 text-[9.5px] font-ui text-muted-lab">
                                    {longKey && (
                                        <span>Long: <span className="text-[hsl(var(--text-2))]">{longKey}</span></span>
                                    )}
                                    {shortKey && (
                                        <span>Short: <span className="text-[hsl(var(--text-2))]">{shortKey}</span></span>
                                    )}
                                </div>
                            )}

                            {/* Stats grid */}
                            <div className="grid grid-cols-4 sm:grid-cols-6 lg:grid-cols-11 gap-x-3 gap-y-2">
                                {[
                                    { label: "Net R",   value: fmtR(stats.netR),        cls: stats.netR >= 0 ? "text-[hsl(var(--success))]" : "text-[hsl(var(--danger))]", bold: true },
                                    { label: "Trades",  value: String(stats.tradeCount), cls: "text-[hsl(var(--text))]" },
                                    { label: "Win %",   value: fmtPct(stats.winRate),    cls: "text-[hsl(var(--text))]" },
                                    { label: "PF",      value: fmtPF(stats.profitFactor), cls: "text-[hsl(var(--text))]" },
                                    { label: "Expect.", value: fmtR(stats.expectancy),   cls: (stats.expectancy ?? 0) >= 0 ? "text-[hsl(var(--success))]" : "text-[hsl(var(--danger))]" },
                                    { label: "Max DD",  value: stats.maxDD != null ? `${stats.maxDD.toFixed(2)}R` : "—", cls: "text-[hsl(var(--danger))]" },
                                    { label: "Long N",  value: String(stats.longCount),  cls: "text-[hsl(var(--text-2))]" },
                                    { label: "Short N", value: String(stats.shortCount), cls: "text-[hsl(var(--text-2))]" },
                                    { label: "Long R",  value: fmtR(stats.longNetR),     cls: stats.longNetR >= 0 ? "text-[hsl(var(--success))]" : "text-[hsl(var(--danger))]" },
                                    { label: "Short R", value: fmtR(stats.shortNetR),    cls: stats.shortNetR >= 0 ? "text-[hsl(var(--success))]" : "text-[hsl(var(--danger))]" },
                                ].map(({ label, value, cls, bold }) => (
                                    <div key={label} className="flex flex-col gap-0.5">
                                        <span className="text-[8.5px] font-ui uppercase tracking-wider text-muted-lab">
                                            {label}
                                        </span>
                                        <span className={[
                                            "text-[12px] font-num tabular-nums leading-tight",
                                            bold ? "font-semibold" : "",
                                            cls,
                                        ].join(" ")}>
                                            {value}
                                        </span>
                                    </div>
                                ))}
                            </div>
                        </div>
                    );
                })}
            </div>
        </div>
    );
}

export default DirectionalScenariosPanel;
